### PR TITLE
Add support for PHP 7.4 in composer.json

### PR DESCRIPTION
**Pull request by fnogatz**

### CODE REVIEW

**Comment by kamzata** [comment]
Please, merge it so I'll be able to install it using composer.

**Comment by gwharton** [comment]
++++1

**Comment by Jieiku** [comment]
I tested this manually:

`"php": "~7.0.0|~7.1.0|~7.2.0|~7.3.0|~7.4.0",`

works perfectly on my install, this should be merged.

**Comment by fnogatz** [comment]
FYI: Some weeks ago, I created the fork [fnogatz/magento2-matomo](https://github.com/fnogatz/magento2-matomo), which can be installed on Magento 2.4 using composer via `composer require chessio/module-matomo`.

**Comment by amenk** [comment]
@fnogatz Thanks for the fork - do you plan to maintain that for a longer term? Not sure if we should use the original module or yours, of course it's nicer if everything is called "Matomo" in the module :-)

**Comment by fnogatz** [comment]
Hey @amenk, thanks for asking. My intention is to maintain the fork until this original module by @henkelund is maintained again. I won't write new features, but will ensure compatibility with the latest PHP and Magento versions. Though I'm very happy to include any PR!

NB: I renamed everything from *Piwik* to *Matomo* in my fork – except the configuration settings, so the module is still compatible with the original version from @henkelund.

**Comment by henkelund** [comment]
Hey, I'm sorry for not paying attention to this, thanks for the PR

**Comment by amenk** [comment]
@henkelund Hey, cool, thanks :-) So now the strategic question is: Shall we proceed with the fork or not ;-) @fnogatz Renamed the package to Matomo and the question is if this should be done here as well. I think two maintained - co-existing - packages will cause confusion :)

**Comment by henkelund** [comment]
@amenk Since I'm not using this module in any projects of my own anymore I'm not paying much attention to what's going in on Matomo-land. I've opened #49 with a proposal to abandon this package in favor of @fnogatz 's fork.

So, yes, I agree with you, it's better if the module is maintained in one place, by people with active interest in its maintenance.

**Pull request merged**
