### PR TITLE
Mark as abandoned in favor of chessio/module-matomo

### PR DESCRIPTION
**Pull request by henkelund**
Hi @fnogatz, thanks for maintaining a fork of this module. As I have no use of this module anymore myself, I don't pay much attention to the activity in this repo. So, I would like to abandon the composer package in favor of yours, if that's ok with you, of course.

### CODE REVIEW

**Comment by fnogatz** [comment]
Hi @henkelund, thank you for coming back to this. You did a great job with the `henhed/module-piwik` module, thank you a lot for all the work you put in!

Quoting some of the discussion of #45 here, since they are related to this issue. @amenk [wrote](https://github.com/henkelund/magento2-henhed-piwik/pull/45#issuecomment-826091253):

> So now the strategic question is: Shall we proceed with the fork or not ;-) @fnogatz Renamed the package to Matomo and the question is if this should be done here as well. I think two maintained - co-existing - packages will cause confusion :)

@henkelund's [answer](https://github.com/henkelund/magento2-henhed-piwik/pull/45#issuecomment-826093223):

> Since I'm not using this module in any projects of my own anymore I'm not paying much attention to what's going in on Matomo-land. I've opened #49 with a proposal to abandon this package in favor of @fnogatz 's fork.
>
> So, yes, I agree with you, it's better if the module is maintained in one place, by people with active interest in its maintenance.

I'm fine with whatever way you prefer: Regarding this GitHub repository, you could (a) simply abandon this repo here as suggested, with a link to the fork in `README.md`, (b) add me as a collaborator in this repo (*Settings » Manage Access*), so I could merge the changes of my fork back to this repository, or (c) transfer ownership of this repo to me (*Settings » Options » Transfer ownership*), so I could merge the changes of my fork back to this repo and still have access to its settings and CI and we keep track of all open issues, etc.

Besides the GitHub repository, I think it's the best way to abandon the `henhed/module-piwik` module in favor to `chessio/module-matomo` on packagist via the `composer.json`, as suggested in this PR.

Maybe @amenk also wants to elaborate on this, since they are currently working on a new feature for this module.

**Comment by henkelund** [comment]
@fnogatz Good points. Also, the official Matomo integrations page is linking to this repo so it may be the least disruptive option for everybody to keep things here. Iv'e invited you as a collaborator to this repo.

Edit: Thanks for the kind words <3

**Comment by amenk** [comment]
Probably both options are fine.

But as the class prefix and composer package would change and this package still has Piwik in the name, using @fnogatz's repository might make more sense.

For sure the link on the Matomo integration page can be changed.

**Comment by henkelund** [comment]
I'll leave that decision to you guys, either way is OK with me.

**Comment by fnogatz** [comment]
Just a short note, @henkelund: when transferring and renaming the repo via the project's settings, GitHub does all the magic behind the scenes. Most importantly, all links forward to the new corresponding pages, i.e. at the end, this issue's URL `https://github.com/henkelund/magento2-henhed-piwik/pull/49` would simply forward to `https://github.com/fnogatz/magento2-matomo/pull/49`. Even `git clone` with the old address will continue to work.<sup>1</sup> However, this way you lose the credit for the work you've done in your GitHub profile. So I'm totally fine with manually setting links to the new repo instead.

<em><sup>1</sup>For instance, we did similar with the repositories https://github.com/mndrix/tap and https://github.com/jonakalkus/dcg-visualiser, for which I am the maintainer now, and which forward to my user's namespace. If we want to follow this route, I would first have to temporarily remove my own fork, as otherwise transferring does not work.</em>

**Comment by henkelund** [comment]
@fnogatz That's totally fine, just tell me what I need to do. (Wouldn't transferring work anyway since the repos don't have the same name?)

**Comment by fnogatz** [comment]
We can try it, though I'm pretty sure the last time I checked it did not work, probably because GitHub keeps track of the "fork of" relation and does not allow a user to have both a repo and its own fork. But we'll see. Just go to the [project's settings](https://github.com/henkelund/magento2-henhed-piwik/settings) (the *Options* tab on the left should already be active), go to *Danger Zone*, where there is a field *Transfer ownership*.

**Comment by henkelund** [comment]
@fnogatz Done. No error message on my side.

**Comment by fnogatz** [comment]
Alright, thank you, @henkelund. The forwards work as expected, see for instance [`https://github.com/henkelund/magento2-henhed-piwik/pull/49`](https://github.com/henkelund/magento2-henhed-piwik/pull/49). I created a new MR #50 to rebase all changes made in the meantime back to this repository. This MR here remains open as we have to indicate the name change and former location in the `README.md`, and I still have to abandon the former package via `composer.json`. I will happily do all these things in the coming days :)

**Comment by fnogatz** [comment]
The Packagist module [`henhed/module-piwik`](https://packagist.org/packages/henhed/module-piwik) is already marked as abandoned and links to the new package. I just made all changes required regarding the updated GitHub repository, so I'll close this PR here. In case we need to correct some old links somewhere, we could just open a separate issue.

**Pull request closed without merging**
