### PR TITLE
Php 8.1 compatibility

### PR DESCRIPTION
**Pull request by zamu87**
Added php 8.1 in composer.json and fixed `trim(): Passing null to parameter #1 ($string) of type string is deprecated`

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
Hi @fnogatz,
Could you please review this pull request?

**Comment by DominikFluegelEcoplan** [comment]
Hi @fnogatz ,

is there a possibility to review the pull request? Would be a pleasure!

Greetings

**Comment by stephansteiner** [comment]
Magento 2.4.5(-p1) has been released, we need to migrate all shops to 2.4.5 as soon as possible because of end of life of php 7.4.
Please review the pull request. Thank you

**Comment by sebastian-ehrling** [comment]
Hi @fnogatz 
it is possible to merge this pull request?

thx a lot!

**Comment by SerhiiMandrykin** [comment]
Hi @fnogatz 
Do you think you can merge it?

Thanks

**Comment by fnogatz** [comment]
Thank you for the valuable contribution, @zamu87!

**Pull request merged**
