### PR TITLE
Add PHP7.3 support to composer.json

### PR DESCRIPTION
**Pull request by antonio30111988**

### CODE REVIEW

**Comment by ihor-sviziev** [comment]
@henkelund could you review this PR?

**Comment by ihor-sviziev** [comment]
@henkelund thank you! Could you also add git tag on latest commit in order to have stable module version?

**Comment by henkelund** [comment]
@ihor-sviziev Sure: https://github.com/henkelund/magento2-henhed-piwik/releases/tag/v2.0.4

**Comment by ihor-sviziev** [comment]
@henkelund thank you so much!

**Pull request merged**
